Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,11 +1,9 @@
 # This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Python application
+name: Testing Python Application
 
 on:
-  push:
-    branches: [ "staging" ]
   pull_request:
     branches: [ "staging" ]
 
@@ -13,8 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  build:
-
+  test:
     runs-on: ubuntu-latest
 
     steps:
@@ -37,3 +34,12 @@ jobs:
     - name: Test with pytest
       run: |
         pytest -s
+    - name: Check if tests passed
+      run: |
+        if [ $? -eq 0 ]; then
+          echo "Tests passed!"
+          exit 0
+        else
+          echo "Tests failed. Please fix before merging."
+          exit 1
+        fi
